server:
  port: 8011
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: 192.168.89.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
    alibaba:
      seata:
        # 分布式事务 事务分组配置（必配）
        tx-service-group: my_test_tx_group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC
    username: root
    password: mzllsy
# seata 配置
seata:
  # 注册中心配置
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      application: seata-server
      username: ${spring.cloud.nacos.discovery.username}
      password: ${spring.cloud.nacos.discovery.password}
      group: SEATA_GROUP
  # 配置中心配置
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      username: ${spring.cloud.nacos.discovery.username}
      password: ${spring.cloud.nacos.discovery.password}
      group: ${seata.registry.nacos.group}