server:
  port: 8014
spring:
  application:
    name: product-service
  cloud:
    nacos:
      server-addr: 192.168.79.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        # 实例临时性配置，false为永久实例，即使状态不正常也不会被踢出注册中心
        ephemeral: false