server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hcmp?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: mzllsy